import { chromium } from "playwright-core";
const bin="/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell";
const b=await chromium.launch({executablePath:bin,args:["--no-sandbox"]});
const ctx=await b.newContext({viewport:{width:1440,height:900}});
await ctx.addInitScript(()=>{try{sessionStorage.setItem("aurea_seen","1");localStorage.setItem("aurea-cookie-consent","declined")}catch{}});
const p=await ctx.newPage();
await p.goto("http://127.0.0.1:3100/uslugi/landing/",{waitUntil:"networkidle"});
await p.waitForTimeout(600);
await p.evaluate(()=>{const el=document.querySelector('.sec--light');if(el)el.scrollIntoView({block:'start'});});
await p.waitForTimeout(700);
await p.screenshot({path:"/tmp/shots/v5-service-light2.png"});
await b.close();console.log("ok");
